var config = {
    title: "Givatayim, Israel",
    imageName: "image-resize.jpg",
    location: "Givatayim Observatory",
    latitude: 32.07,
    longitude: 34.815,
    az: 180,
    camera: "ASI120MC-S",
    computer: "Raspberry Pi Model B",
    owner: "Givatayim Observatory",
    auroraMap: "north",
    overlaySize: 875,
    overlayOffsetLeft: 0,
    overlayOffsetTop: 0,
}
